import { CHARACTER_INT_LIMITS } from './validation-limits.js'

/**
 * CombatState 欄位防爆絕對值上限；純防 JSONB 塞爆，不承載 SRD 規則語意
 * （規則上限請見 `rules/`）。`_ABS_MAX` 後綴代表 ±cap；無後綴代表 0..max。
 */
export const COMBAT_STATE_LIMITS = {
  HP_TEMP_MAX: CHARACTER_INT_LIMITS.GENERAL_INT_MAX,
  HP_MAX_ADJUSTMENT_ABS_MAX: CHARACTER_INT_LIMITS.GENERAL_INT_MAX,
  AC_ADJUSTMENT_ABS_MAX: CHARACTER_INT_LIMITS.SMALL_INT_MAX,
  SPEED_ADJUSTMENT_ABS_MAX: CHARACTER_INT_LIMITS.SMALL_INT_MAX,
  SAVING_THROW_ADJUSTMENT_ABS_MAX: CHARACTER_INT_LIMITS.SMALL_INT_MAX,
  FEATURE_USES_SPENT_MAX: CHARACTER_INT_LIMITS.SMALL_INT_MAX,
  HIT_DICE_USED_MAX: CHARACTER_INT_LIMITS.SMALL_INT_MAX,
  SPELL_SLOTS_USED_MAX: CHARACTER_INT_LIMITS.SMALL_INT_MAX,
  PACT_SLOTS_USED_MAX: CHARACTER_INT_LIMITS.SMALL_INT_MAX,
} as const
